route:
  group_by: ['...']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m
  receiver: "telegram-warning"
  routes:
  - receiver: "telegram-critical"
    matchers:
    - severity="critical"

receivers:
  - name: 'telegram-warning'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '6325881956:AAHUy48Garq5wpMo2g3fC9OHUVTBHxkIWio'
      chat_id: -4179371742
  - name: 'telegram-critical'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '6325881956:AAHUy48Garq5wpMo2g3fC9OHUVTBHxkIWio'
      chat_id: -4132205397
