global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      site: 'prod'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
rule_files:
  - /etc/gap-1/alerts/*.yml
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['10.10.240.121:9100']

  - job_name: mysql
    static_configs:
      - targets:
        - 10.10.240.121:9104
          #relabel_configs:
          #- source_labels: [__address__]
          #target_label: __param_target
          #- source_labels: [__param_target]
          #target_label: instance
          #- target_label: __address__
          #replacement: 10.10.240.121::9104

  - job_name: nginx
    static_configs:
      - targets:
        - 10.10.240.121:9113

  - job_name: php-fpm
    static_configs:
      - targets:
          - 10.10.240.121:9114

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://10.10.240.121:8000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.10.240.121:9115  # The blackbox exporter's real hostname:port.
#remote_write:
#  - url: http://localhost:8428/api/v1/write
#    queue_config:
#      max_samples_per_send: 10000
#      capacity: 20000
#      max_shards: 30
